- name: destroy the openshift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    become_override: false
    
  tasks:
    - name: gather cluster facts
      include_role:
        name: roles/gather-cluster-facts

    - name: get the installer binary
      include_role:
        name: roles/installer-binary

    - name: destroy the openshift cluster
      include_role:
        name: roles/destroy-cluster