- name: bootstrap the openshift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    become_override: false

  tasks:
    - name: gather cluster facts
      include_role:
        name: roles/gather-cluster-facts

#    - name: prepare the platform
#      include_role:
#        name: roles/prepare-platform

    - name: setup the cde
      when: platform_deploy_devspaces | bool == true
      include_role:
        name: roles/setup-cde

    - name: setup jumpstarter
      when: platform_deploy_jumpstarter | bool == true
      include_role:
        name: roles/setup-jumpstarter

    - name: setup the builder
      when: platform_deploy_builder | bool == true
      include_role:
        name: roles/setup-builder

    - name: show web console url
      debug:
        msg: "Access the web-console: https://console-openshift-console.apps.{{ cluster_name }}.{{ cluster_sub_domain }}"