- name: bootstrap the openshift cluster
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    become_override: false

  tasks:
    - name: gather cluster facts
      include_role:
        name: roles/gather-cluster-facts

    - name: prepare the platform
      include_role:
        name: roles/setup-platform

    - name: show web console url
      debug:
        msg: "Access the web-console: https://console-openshift-console.apps.{{ cluster_name }}.{{ cluster_sub_domain }}"