
- name: create builder namespace and stuff
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - app-builder.yml.j2

- name: wait for the builder app to be ready
  k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: auto-builder
    namespace: "{{ gitops_namespace }}"
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_application
  retries: 180
  delay: 10
  until:
    - r_application.resources | length > 0
    - r_application.resources[0].status is defined
    - r_application.resources[0].status.sync is defined
    - r_application.resources[0].status.sync.status is defined
    - r_application.resources[0].status.sync.status == 'Synced'

#- name: give platform_user_group viewer access to platform_builder_namespace
#  when: platform_deploy_builder | bool == true
#  shell: |
#    oc adm policy add-role-to-group view {{ platform_user_group }} \
#      -n {{ platform_builder_namespace }} \
#      --kubeconfig="$HOME/.kube/{{ cluster_fqn }}"

#- name: give jumpstarter_user_group edit access to platform_jumpstarter_namespace
#  when: platform_deploy_jumpstarter | bool == true
#  shell: |
#    oc adm policy add-role-to-group edit {{ jumpstarter_user_group }} \
#      -n {{ platform_jumpstarter_namespace }} \
#      --kubeconfig="$HOME/.kube/{{ cluster_fqn }}"