---
# defaults

# default jumpstarter groups
jumpstarter_admin_group: "jumpstarter-admins"
jumpstarter_user_group: "jumpstarter-users"

# keycloak subscription
keycloak_subscription_channel: "stable-v26.6"
keycloak_subscription_starting_csv: "rhbk-operator.v26.6.4-opr.1" 
