
- name: create devspaces app
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - app-devspaces.yml.j2

- name: wait for the devspaces app to be ready
  k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: auto-devspaces
    namespace: "{{ gitops_namespace }}"
    kubeconfig: "{{ local_kubeconfig_file }}"
  register: r_application
  retries: 180
  delay: 10
  until:
    - r_application.resources | length > 0
    - r_application.resources[0].status is defined
    - r_application.resources[0].status.sync is defined
    - r_application.resources[0].status.sync.status is defined
    - r_application.resources[0].status.sync.status == 'Synced'

- name: pause to allow the operator to settle
  pause:
    seconds: 120

- name: devspaces config
  k8s:
    definition: "{{ lookup('template', item ) | from_yaml }}"
    state: present
    apply: yes
    kubeconfig: "{{ local_kubeconfig_file }}"
  loop:
    - configmap-jumpstarter.yml.j2
    - configmap-builder.yml.j2